# Generated by Django 5.2.7 on 2025-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tamano',
        ),
        migrations.AlterField(
            model_name='documento',
            name='rutaDocumento',
            field=models.FileField(blank=True, help_text='Archivo físico del documento', null=True, upload_to='documentos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='versiondocumento',
            name='rutaArchivo',
            field=models.FileField(blank=True, help_text='Archivo físico de esta versión', null=True, upload_to='versiones/%Y/%m/%d/'),
        ),
    ]
