# Generated by Django 5.2.7 on 2025-10-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documento_tamano_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='versiondocumento',
            name='documentos__usuario_2c01d2_idx',
        ),
        migrations.RenameField(
            model_name='versiondocumento',
            old_name='usuario',
            new_name='creado_por',
        ),
        migrations.AddField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='versiondocumento',
            index=models.Index(fields=['creado_por'], name='documentos__creado__030959_idx'),
        ),
    ]
