# Generated by Django 5.2.7 on 2025-10-13 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_usuariorol_fechaasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permiso_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permiso_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rol',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rol_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rol',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rol_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolpermiso_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolpermiso_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuariorol_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuariorol_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
