# Generated by Django 5.2.7 on 2025-10-13 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caso',
            name='casos_caso_estado_29f25d_idx',
        ),
        migrations.RemoveIndex(
            model_name='caso',
            name='casos_caso_fechaIn_89fae5_idx',
        ),
        migrations.AddField(
            model_name='carpeta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpeta_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpeta_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipocaso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipocaso_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipocaso',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipocaso_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expediente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expediente_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expediente',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expediente_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parteprocesal',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parteprocesal_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parteprocesal',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parteprocesal_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
